# Generated by Django 5.2.8 on 2025-12-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Petadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
