# Generated by Django 5.2.8 on 2025-12-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Petadmin', '0002_delete_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=20)),
                ('admin_email', models.EmailField(max_length=100)),
                ('admin_password', models.CharField(max_length=10)),
            ],
        ),
    ]
