# Generated by Django 5.2.8 on 2026-01-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petadmin', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_admin',
            name='admin_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pro_admin',
            name='admin_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pro_admin',
            name='admin_password',
            field=models.CharField(max_length=100),
        ),
    ]
