# Generated by Django 5.0.4 on 2026-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petadmin', '0004_alter_pro_admin_admin_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
