# Generated by Django 5.2.8 on 2026-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petadmin', '0006_groomingservice_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaycarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groomingservice',
            name='icon',
            field=models.CharField(max_length=50),
        ),
    ]
