# Generated by Django 5.0.4 on 2026-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petadmin', '0007_daycareplan_alter_groomingservice_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycareplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='daycareplan',
            name='duration_days',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='daycareplan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
