# Generated by Django 5.0.4 on 2026-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Petadmin', '0008_daycareplan_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daycareplan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='daycareplan',
            name='price',
        ),
        migrations.AddField(
            model_name='daycareplan',
            name='max_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='daycareplan',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=6),
            preserve_default=False,
        ),
    ]
