# Generated by Django 5.2.8 on 2025-12-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_registration_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctorImages/'),
        ),
    ]
