# Generated by Django 5.2.8 on 2026-01-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_registration_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
