# Generated by Django 5.2.8 on 2026-01-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_registration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_registration',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
