# Generated by Django 5.0.4 on 2026-01-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_registration_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_registration',
            name='is_checkout',
            field=models.BooleanField(default=True),
        ),
    ]
