# Generated by Django 5.2.8 on 2025-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_registration',
            name='username',
            field=models.CharField(default='True', max_length=100),
        ),
    ]
