# Generated by Django 5.0.4 on 2026-01-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.CharField(max_length=15)),
                ('services', models.JSONField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.user_registration')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
