# Generated by Django 5.0.4 on 2026-01-29 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_groomingbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomingbooking',
            name='total_duration',
            field=models.PositiveIntegerField(default=0, help_text='Total duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon (🛁 ✂️ 💅 🐾)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='GroomingSlotLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.user_registration')),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
