# Generated by Django 5.0.4 on 2026-01-29 02:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_groomingbooking_total_duration_service_duration_and_more'),
        ('volunteer', '0006_volunteernotification_volunteerpet_volunteertask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groomingbooking',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='groomingbooking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='end_time',
            field=models.TimeField(default=datetime.time(2, 30, 12, 173695)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='start_time',
            field=models.TimeField(default=datetime.time(2, 30, 47, 197577)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='groomingbooking',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volunteer.volunteer_registration'),
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groomingbooking',
            name='total_duration',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='groomingbooking',
            name='time',
        ),
    ]
