# Generated by Django 5.2.8 on 2026-01-29 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_alter_groomingbooking_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daycarebooking',
            unique_together={('date', 'start_time')},
        ),
        migrations.AlterUniqueTogether(
            name='groomingbooking',
            unique_together={('date', 'start_time')},
        ),
        migrations.CreateModel(
            name='DaycareSlotLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.user_registration')),
            ],
            options={
                'unique_together': {('date', 'time')},
            },
        ),
    ]
