# Generated by Django 5.2.8 on 2026-01-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_alter_daycarebooking_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycarebooking',
            name='pet_type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
