# Generated by Django 5.2.8 on 2026-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0010_rename_phone_groomingbooking_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('grooming', 'Grooming'), ('daycare', 'Daycare')], default='grooming', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
