# Generated by Django 5.0.4 on 2026-02-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0012_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
