# Generated by Django 5.0.4 on 2026-02-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0013_service_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Visited', 'Visited'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
