# Generated by Django 5.2.8 on 2025-11-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(default='True', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('proof', models.FileField(default=True, upload_to='volunteer_docs')),
                ('phone', models.CharField(default='True', max_length=15)),
                ('address', models.TextField(default='True')),
            ],
        ),
    ]
