# Generated by Django 5.2.8 on 2025-11-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer_registration',
            name='username',
        ),
        migrations.AddField(
            model_name='volunteer_registration',
            name='skills',
            field=models.CharField(default='True', max_length=30),
        ),
    ]
