# Generated by Django 5.2.8 on 2026-01-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_remove_volunteer_registration_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_registration',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
