# Generated by Django 5.0.4 on 2026-01-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_volunteerattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer_registration',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
