# Generated by Django 5.0.4 on 2026-01-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_alter_volunteer_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer_registration')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer_registration')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('task_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], default='upcoming', max_length=30)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer.volunteer_registration')),
            ],
        ),
    ]
