# Generated by Django 5.0.4 on 2026-01-29 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_volunteernotification_volunteerpet_volunteertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteernotification',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='volunteernotification',
            name='title',
            field=models.CharField(default='System Notification', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteernotification',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='volunteer.volunteer_registration'),
        ),
    ]
