# Generated by Django 5.0.4 on 2026-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_volunteernotification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer_registration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='volunteer_registration',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteer_registration',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='volunteer_registration',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_docs'),
        ),
        migrations.AlterField(
            model_name='volunteer_registration',
            name='skills',
            field=models.CharField(max_length=30),
        ),
    ]
