# Generated by Django 5.0.4 on 2026-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_volunteer_registration_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('proof', models.FileField(upload_to='volunteer_applications/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('authorization_code', models.CharField(blank=True, max_length=12, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
