# Generated by Django 5.0.4 on 2026-02-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_volunteerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='proof',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='code_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
