# Generated by Django 5.0.4 on 2026-02-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_remove_volunteerapplication_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='code_expires_at',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='code_used',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='volunteer_proofs/'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='authorization_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
